// 회사 소개 요약 — Wikipedia REST 요약 API(CC BY-SA)에서 보강한 데이터.
// scripts/enrich_company_summaries.py 로 생성하고, 사람이 git diff 로 검수한다.
// company-facts.ts 의 검수된 QID·sitelink 만 재사용 — 새 이름 매칭 없음(오매칭 0).
// CC BY-SA 라이선스: 표시 시 문서 링크(url)로 출처를 함께 노출할 것.

export interface CompanySummary {
  /** 위키 문서 언어(ko 우선, 없으면 en). */
  lang: "ko" | "en";
  /** 위키 문서 제목(검수용). */
  title: string;
  /** 요약 첫 문단(플레인 텍스트, 문장 경계 절단). */
  extract: string;
  /** 문서 URL(출처 표기용). */
  url: string;
}

export const COMPANY_SUMMARIES: Record<string, CompanySummary> = {
  "adyen": { lang: "ko", title: "아디옌", extract: "아디옌(영어: Adyen)는 네덜란드의 글로벌 결제 플랫폼 기업이다. 수리남어로 '처음부터 다시 시작하자'라는 뜻의 아디옌은 2006년 네덜란드 암스테르담에서 창업되었으며 2018년 현재 아디옌은 전 세계 온라인 결제 시장에서 가장 빠르게 성장하는 회사 중의 하나가 되었다. 아디옌은 세계 어느 곳에서나 어느 장치로도 고객의 결제를 처리할 수 있는 단일 플랫폼을 구성하고 있는데 이것은 모바일 또는 POS 단말기에서 그리고 여러 마켓 플레이스에서 신용카드, 직불카드 그리고 은행 이체를 통하여 가능하며, 또한 아디옌을 이용하는 비즈니스 업체들은 아디옌이 제공하는 고객 분석 데이터, 수익 최적화 및 위험 관리 자료 등을 이용할 수 있다.", url: "https://ko.wikipedia.org/wiki/%EC%95%84%EB%94%94%EC%98%8C" },
  "affirm": { lang: "en", title: "Affirm Holdings", extract: "Affirm Holdings, Inc. is an American financial technology company and a point-of-sale lender. Founded in 2012 by PayPal co-founder Max Levchin, it is the largest U.S. based buy now, pay later (BNPL) financier. As of 2025, Affirm reports nearly 27 million users and processing $37 billion in annual payments.", url: "https://en.wikipedia.org/wiki/Affirm_Holdings" },
  "airbnb": { lang: "ko", title: "에어비앤비", extract: "에어비앤비(영어: Airbnb, Inc.)는 2008년 8월 시작된 세계 최대의 숙박 공유 서비스이다. 자신의 방이나 집, 별장 등 사람이 지낼 수 있는 모든 공간을 임대할 수 있다. 2013년 기준, 192개국 3만 4800여 개 장소에 대한 숙박을 중개하고 있으며, 2초당 한 건 씩 예약이 이뤄지고 있다. 2013년 1월 29일 대한민국 진출을 발표했다.", url: "https://ko.wikipedia.org/wiki/%EC%97%90%EC%96%B4%EB%B9%84%EC%95%A4%EB%B9%84" },
  "airbyte": { lang: "en", title: "Airbyte", extract: "Airbyte is an open-source data integration platform that allows organizations to recompile and synchronize multi-source data in places such as data warehouses, data lakes or databases. Founded in 2020 with investments in San Francisco, California, the company offers multiple implementation offers, including cloud integration, local, and hybrid integration of data.", url: "https://en.wikipedia.org/wiki/Airbyte" },
  "airtable": { lang: "ko", title: "에어테이블", extract: "에어테이블(Airtable)은 샌프란시스코에 본사를 둔 클라우드 협업 서비스다.", url: "https://ko.wikipedia.org/wiki/%EC%97%90%EC%96%B4%ED%85%8C%EC%9D%B4%EB%B8%94" },
  "algolia": { lang: "en", title: "Algolia", extract: "Algolia is a French proprietary search-as-a-service platform, with its headquarters in San Francisco and offices in Paris and London. Its main product is a web search platform for individual websites.", url: "https://en.wikipedia.org/wiki/Algolia" },
  "amplitude": { lang: "en", title: "Amplitude, Inc.", extract: "Amplitude is an American publicly traded company that develops digital analytics software. The company was listed publicly on the Nasdaq stock exchange under the ticker symbol AMPL on September 28, 2021.", url: "https://en.wikipedia.org/wiki/Amplitude%2C_Inc." },
  "angellist": { lang: "en", title: "AngelList", extract: "AngelList is an American software company for fundraising and connecting startups, angel investors, and limited partners. Founded in 2010, it started as an online introduction board for tech startups that needed seed funding. Since 2015, the site allows startups to raise money from angel investors free of charge. Created by serial entrepreneur Naval Ravikant and Babak Nivi in 2010, Avlok Kohli has been leading AngelList as its CEO since 2019.", url: "https://en.wikipedia.org/wiki/AngelList" },
  "asos": { lang: "en", title: "ASOS plc", extract: "ASOS plc is a British online fast-fashion and cosmetic retailer. The company was founded in 2000 in London, primarily aimed at young adults. The website sells over 850 brands as well as its own range of clothing and accessories, and ships to all 196 countries from fulfilment centres in the United Kingdom, the United States, and Europe.", url: "https://en.wikipedia.org/wiki/ASOS_plc" },
  "beamery": { lang: "en", title: "Beamery", extract: "Beamery is a privately held global human resource management software company. It is headquartered in London, United Kingdom, and operates in Germany, Singapore and the United States. Their main product is an AI-powered talent platform meant to assist other organizations in managing employees.", url: "https://en.wikipedia.org/wiki/Beamery" },
  "betterup": { lang: "en", title: "BetterUp", extract: "BetterUp is an American digital coaching and workforce development company founded in 2013. It was officially launched in 2016 and raised a total of $570 million. The company specializes in one-on-one coaching, behavioral sciences, and artificial intelligence to provide personal and professional development for individuals and companies.", url: "https://en.wikipedia.org/wiki/BetterUp" },
  "bitpanda": { lang: "en", title: "Bitpanda", extract: "Bitpanda GmbH is an Austrian company headquartered in Vienna. Bitpanda provides a cryptocurrency broker, commodities and securities trading, and ETFs via their website and mobile app. In 2021, Bitpanda achieved a valuation of over US$4 billion. The company was the first Austrian start-up to meet the criteria for unicorn status.", url: "https://en.wikipedia.org/wiki/Bitpanda" },
  "brex": { lang: "en", title: "Brex", extract: "Brex, a subsidiary of Capital One, is an American fintech company that offers credit cards and cash management accounts as well as a spend management software platform to startup technology companies.", url: "https://en.wikipedia.org/wiki/Brex" },
  "celonis": { lang: "en", title: "Celonis", extract: "Celonis SE is an American-German data processing company that offers software as a service (SaaS) to improve business processes. It is headquartered in Munich, Germany with a secondary headquarters New York, United States.", url: "https://en.wikipedia.org/wiki/Celonis" },
  "chime": { lang: "en", title: "Chime (company)", extract: "Chime Financial, Inc. is an American financial technology company based in San Francisco, California. It provides fee-free mobile banking services through partnerships with two national banks, Stride Bank and The Bancorp Bank. The company offers fee-free checking and savings accounts, debit cards, and other financial products through its mobile application.", url: "https://en.wikipedia.org/wiki/Chime_(company)" },
  "circleci": { lang: "ko", title: "CircleCI", extract: "CircleCI는 DevOps 관행을 구현하는 데 사용할 수 있는 지속적 통합(Continuous Integration) 및 지속적 전달(Continuous Delivery) 플랫폼이다. 이 회사는 2011년 9월에 설립되었으며 2021년 기준으로 3억 1,500만 달러의 벤처 캐피털 자금을 유치하고 17억 달러의 가치로 평가받은 바 있다. CircleCI는 세계에서 가장 인기 있는 CI/CD 플랫폼 중 하나이다.", url: "https://ko.wikipedia.org/wiki/CircleCI" },
  "cohere": { lang: "en", title: "Cohere", extract: "Cohere Inc. is a Canadian multinational technology company focused on artificial intelligence. Cohere specializes in large language models and AI products for regulated industries, particularly the finance, healthcare, manufacturing, and energy fields, as well as the public sector.", url: "https://en.wikipedia.org/wiki/Cohere" },
  "coinbase": { lang: "en", title: "Coinbase", extract: "Coinbase Global, Inc. is an American cryptocurrency exchange. It was founded in 2012 by Brian Armstrong and Fred Ehrsam. Coinbase has over 100 million users, and is the largest U.S. based cryptocurrency exchange as well as the world's biggest bitcoin custodian, as of 2024.", url: "https://en.wikipedia.org/wiki/Coinbase" },
  "confluent": { lang: "en", title: "Confluent", extract: "Confluent, Inc. is an American technology company headquartered in Mountain View, California. Confluent was founded by Jay Kreps, Jun Rao and Neha Narkhede on September 23, 2014, in order to commercialize an open-source streaming platform Apache Kafka, created by the same founders while working at LinkedIn in 2008 as a B2B infrastructure company.", url: "https://en.wikipedia.org/wiki/Confluent" },
  "contentful": { lang: "en", title: "Contentful", extract: "Contentful is a German-American headless content management system (CMS), founded in 2013 in Berlin, Germany, by Sascha Konietzke and Paolo Negri. The company and the platform are both called Contentful.", url: "https://en.wikipedia.org/wiki/Contentful" },
  "coreweave": { lang: "ko", title: "코어위브", extract: "코어위브(영어: CoreWeave)는 미국 리빙스턴에 본사를 둔 인공지능 클라우드 컴퓨팅 스타트업 기업이다. 인공지능 개발자와 기업에 클라우드 기반 그래픽 처리 장치(GPU) 인프라를 제공하는 데 특화되어 있으며, 자체 칩 관리 소프트웨어 개발도 병행한다. 아마존 웹 서비스, 마이크로소프트 애저 등 종합 클라우드 서비스를 제공하는 하이퍼스케일러와 달리 GPU 기반 인공지능/고성능 컴퓨팅 인프라에 집중하는 이러한 사업자는 네오클라우드로 불리며, 코어위브도 이에 해당한다.", url: "https://ko.wikipedia.org/wiki/%EC%BD%94%EC%96%B4%EC%9C%84%EB%B8%8C" },
  "databricks": { lang: "ko", title: "데이터브릭스", extract: "데이터브릭스(Databricks)는 2013년 아파치 스파크의 원조 제작자들이 설립한 글로벌 데이터, 애널리틱스, 인공지능 (AI) 회사이다. 이 회사는 기업이 생성형 인공지능 및 기타 기계 학습 모델을 포함한 데이터와 AI를 구축, 확장 및 관리하는 데 도움이 되는 클라우드 기반 플랫폼을 제공한다.", url: "https://ko.wikipedia.org/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B8%8C%EB%A6%AD%EC%8A%A4" },
  "datadog": { lang: "ko", title: "데이터도그", extract: "데이터도그(Datadog, Inc.)는 SaaS 기반 데이터 분석 플랫폼을 통해 서버, 데이터베이스, 도구 및 서비스 모니터링을 제공하는 클라우드 규모 애플리케이션에 대한 관찰 서비스를 제공하는 미국 회사이다. 뉴욕시에 설립되어 본사를 두고 있는 이 회사는 나스닥 증권 거래소에 상장된 상장 기업이다. 마스코트는 비츠(Bits)라는 이름의 개이다. 인프라 모니터링, 애플리케이션 성능 관리(APM), 로그 분석, 사용자 경험 모니터링, 클라우드 보안 등을 하나의 서비스형 소프트웨어(SaaS) 기반 플랫폼으로 통합 제공한다.", url: "https://ko.wikipedia.org/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%8F%84%EA%B7%B8" },
  "dataiku": { lang: "en", title: "Dataiku", extract: "Dataiku is a French-American artificial intelligence (AI) and machine learning company which was founded in 2013 in Paris, France. In December 2019, Dataiku announced that CapitalG—the late-stage growth venture capital fund financed by Alphabet Inc.—joined Dataiku as an investor and that it had achieved unicorn status. As of 2021, Dataiku is valued at $4.6 billion.", url: "https://en.wikipedia.org/wiki/Dataiku" },
  "discord": { lang: "en", title: "Discord Inc.", extract: "Discord is an American instant messaging and VoIP social platform that allows communication through voice calls, video calls, text messaging, and media. Communication can be private or in virtual communities called \"servers\". A server is a collection of persistent chat rooms and voice channels accessed by invitation links. Discord runs on Windows, macOS, Android, iOS, iPadOS, Linux, and in web browsers.", url: "https://en.wikipedia.org/wiki/Discord" },
  "dropbox": { lang: "ko", title: "드롭박스", extract: "드롭박스(영어: Dropbox 드롭복스[*])는 드롭박스 주식회사(Dropbox, Inc.)가 제공하는, 파일 동기화와 클라우드 컴퓨팅을 이용한 웹 기반의 파일 공유 서비스이다. 2007년 MIT의 졸업자인 드류 휴스턴(Drew Houston)과 아라시 페르도시(Arash Ferdowsi)가 Y 콤비네이터의 벤처기업으로 시작했다.", url: "https://ko.wikipedia.org/wiki/%EB%93%9C%EB%A1%AD%EB%B0%95%EC%8A%A4" },
  "elastic": { lang: "en", title: "Elastic NV", extract: "Elastic is a Dutch-American software company that provides a platform for enterprise search, observability, and cybersecurity. Its product enables users to search and analyze large-scale data, monitor system performance, and detect anomalies. Originally known as Elasticsearch, the company was founded in 2012 in Amsterdam, Netherlands, and has maintained its operational headquarters in both the Netherlands and San Francisco, California, US.", url: "https://en.wikipedia.org/wiki/Elastic_NV" },
  "flexport": { lang: "en", title: "Flexport", extract: "Flexport Inc. is an American multinational corporation that focuses on supply chain management and logistics, including order management, delivery, trade financing, insurance, freight forwarding, and customs brokerage. The company is headquartered in San Francisco, California, has thousands of employees and annual revenues of more than $3.3 billion.", url: "https://en.wikipedia.org/wiki/Flexport" },
  "freetrade": { lang: "en", title: "Freetrade", extract: "Freetrade is a UK-based fintech company founded in 2016 by Adam Dodds and Davide Fioranelli. It operates a mobile trading platform for retail investors in the UK, allowing users to trade equities and ETFs through iOS and Android applications.", url: "https://en.wikipedia.org/wiki/Freetrade" },
  "gitlab": { lang: "en", title: "GitLab Inc.", extract: "GitLab Inc. is an American company that operates and develops GitLab, an open-core DevOps software package that can develop, secure, and operate software. GitLab includes a distributed version control system based on Git, including features such as access control, bug tracking, software feature requests, task management, and wikis for every project, as well as snippets.", url: "https://en.wikipedia.org/wiki/GitLab_Inc." },
  "gocardless": { lang: "en", title: "GoCardless", extract: "GoCardless is a British fintech company that specialises in bank payments including recurring payments, Direct Debit processing and Open Banking. GoCardless is headquartered in London.", url: "https://en.wikipedia.org/wiki/GoCardless" },
  "graphcore": { lang: "en", title: "Graphcore", extract: "Graphcore Limited is a British semiconductor company that develops accelerators for AI and machine learning. It has introduced a massively parallel Intelligence Processing Unit (IPU) that holds the complete machine learning model inside the processor.", url: "https://en.wikipedia.org/wiki/Graphcore" },
  "gusto": { lang: "en", title: "Gusto, Inc.", extract: "Gusto, Inc. is a company that develops payroll, benefits, and human resource management software for businesses based in the United States.", url: "https://en.wikipedia.org/wiki/Gusto%2C_Inc." },
  "improbable": { lang: "en", title: "Improbable (company)", extract: "Improbable Worlds Limited, commonly known as Improbable, is a British technology company headquartered in London, England. It makes metaverse infrastructure and applications, as well as simulation software for video games and corporate use. In fiscal 2022, Improbable reported revenues of £78 million, compared to £22 million in 2021.", url: "https://en.wikipedia.org/wiki/Improbable_(company)" },
  "instacart": { lang: "ko", title: "인스타카트", extract: "인스타카트(Instacart)는 온라인 기반 농작물 배송 서비스이다. 안드로이드, iOS, 그리고 별도로 마련된 웹사이트를 통해 서비스가 제공된다. 고객은 안드로이드 페이와 애플 페이를 통해 각각의 서비스를 이용할 수 있다. 사업에 진행됨에 따라 기존에 점포를 소유하고 있는 식품 회사들과 관계를 맺어가고 있으며 이에 따라 인스타카트 사용자들이 점포 가격에 따라 구입할 수 있다.", url: "https://ko.wikipedia.org/wiki/%EC%9D%B8%EC%8A%A4%ED%83%80%EC%B9%B4%ED%8A%B8" },
  "intercom": { lang: "en", title: "Fin (company)", extract: "Fin, formerly Intercom, Inc., is a software company that provides an AI-driven customer service and messaging platform. It is headquartered in San Francisco with offices in Chicago, Dublin, Sydney and London.", url: "https://en.wikipedia.org/wiki/Fin_(company)" },
  "lyft": { lang: "ko", title: "리프트 (기업)", extract: "리프트(Lyft)는 미국 캘리포니아주 샌프란시스코에 본사를 둔 승차 공유 서비스 기업이다. 리프트는 2012년 6월 짐라이드(Zimride)라는 이름으로 설립되어, 2013년 5월 현재의 이름인 리프트로 사명을 변경하였다. 리프트는 뉴욕, 샌프란시스코, 로스앤젤레스 등을 포함한 북미 지역 300여개의 도시에서 하루에 100만건 이상의 승차 공유 서비스를 제공하고 있다. 북미 지역에서 주요 경쟁자인 우버와 함께 승차 공유 서비스 시장을 선도하는 기업이다.", url: "https://ko.wikipedia.org/wiki/%EB%A6%AC%ED%94%84%ED%8A%B8_(%EA%B8%B0%EC%97%85)" },
  "mercari": { lang: "en", title: "Mercari", extract: "Mercari, Inc. is a Japanese e-commerce company founded in 2013. Their main product, the Mercari marketplace app, was first launched in Japan in July 2013, and has since grown to become Japan's largest community-powered marketplace, with over JPY 10 billion in transactions carried out on the platform each month. Among those Japanese users utilizing one of the country's many community marketplace apps, 94% were found to be using Mercari.", url: "https://en.wikipedia.org/wiki/Mercari" },
  "mixpanel": { lang: "en", title: "Mixpanel", extract: "Mixpanel is a digital analytics service company that tracks user interactions with web and mobile applications. The platform provides product analytics capabilities, including event tracking, user segmentation, retention analysis, and funnel analysis. Data collected is used to build custom reports and measure user engagement and retention.", url: "https://en.wikipedia.org/wiki/Mixpanel" },
  "mongodb": { lang: "en", title: "MongoDB Inc.", extract: "MongoDB, Inc. is an American software company that develops and provides commercial support for the source-available database engine MongoDB, a database for unstructured data. Over the years, the company has expanded the product from its NoSQL roots to have broader appeal to enterprise customers, such as adding ACID and transactions.", url: "https://en.wikipedia.org/wiki/MongoDB_Inc." },
  "monzo": { lang: "en", title: "Monzo", extract: "Monzo Bank Limited, trading as Monzo, is a British online bank based in London. Monzo launched as part of a number of app-based challenger banks entering the UK market.", url: "https://en.wikipedia.org/wiki/Monzo" },
  "n26": { lang: "en", title: "N26", extract: "N26 Bank SE, doing business as N26, and formerly named Papayer GmbH, and Number26 GmbH, is a multinational German fintech and neobank company based in Berlin that offers a variety of financial services to individuals and businesses. N26 was founded in 2013 by Rocket Internet, an incubator, and operates in various European Union member states that are members of the Single Euro Payments Area (SEPA).", url: "https://en.wikipedia.org/wiki/N26" },
  "nextdoor": { lang: "en", title: "Nextdoor", extract: "Nextdoor Holdings, Inc. is an American company that operates a hyperlocal social networking service for neighborhoods. The company was founded in 2008 and is based in San Francisco, California. Nextdoor launched in the United States in October 2011. It is available in eleven countries as of May 2023. In 2024, the company claimed to have 88 million \"neighbors\" as members.", url: "https://en.wikipedia.org/wiki/Nextdoor" },
  "nium": { lang: "en", title: "Nium", extract: "Nium is a Singapore-headquartered cross-border payments company. Initially founded by Prajit Nanu and Michael Bermingham, and launched as a consumer-remittance platform Instarem in 2014. In 2016, the company introduced its B2B payments platform and rebranded as Nium in 2019, subsequently elevating Pratik Gandhi to co-founder in 2021.", url: "https://en.wikipedia.org/wiki/Nium" },
  "pagerduty": { lang: "en", title: "PagerDuty", extract: "PagerDuty, Inc. is an American cloud computing company specializing in a SaaS incident management platform for IT operations departments.", url: "https://en.wikipedia.org/wiki/PagerDuty" },
  "palantir": { lang: "ko", title: "팔란티어 테크놀로지스", extract: "팔란티어 테크놀로지스는 빅 데이터용 소프트웨어 플랫폼을 전문으로 하는 미국의 상장 회사이다. 콜로라도주 덴버에 본사가 있으며, 2003년 피터 틸, 스티븐 코언 (기업인), 조 론즈데일, 알렉스 카프, 네이선 게팅스가 설립했다. 사명은 소설 반지의 제왕에 나오는 천리안 수정구슬 이름에서 가져왔다.", url: "https://ko.wikipedia.org/wiki/%ED%8C%94%EB%9E%80%ED%8B%B0%EC%96%B4_%ED%85%8C%ED%81%AC%EB%86%80%EB%A1%9C%EC%A7%80%EC%8A%A4" },
  "pinterest": { lang: "ko", title: "핀터레스트", extract: "핀터레스트(Pinterest)는 이용자가 스크랩하고자 하는 이미지를 포스팅하고 다른 이용자와 공유하는 소셜 네트워크 서비스이며, 명칭은 핀(Pin)과 인터레스트(Interest)의 합성어이다.", url: "https://ko.wikipedia.org/wiki/%ED%95%80%ED%84%B0%EB%A0%88%EC%8A%A4%ED%8A%B8" },
  "plaid": { lang: "en", title: "Plaid Inc.", extract: "Plaid Inc. is an American financial services company based in San Francisco, California. The company builds a data transfer network that powers fintech and digital finance products.", url: "https://en.wikipedia.org/wiki/Plaid_Inc." },
  "postman": { lang: "ko", title: "포스트맨 (소프트웨어)", extract: "포스트맨(Postman)은 개발자들이 API를 디자인하고 빌드하고 테스트하고 반복하기 위한 API 플랫폼이다. 2022년 4월 기준으로 포스트맨의 등록 사용자는 20,000,000명 이상, 개방 API 수는 75,000개로 보고되었다. 이는 세계 최대의 공개 API 허브를 구성하는 것이다.", url: "https://ko.wikipedia.org/wiki/%ED%8F%AC%EC%8A%A4%ED%8A%B8%EB%A7%A8_(%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4)" },
  "replit": { lang: "ko", title: "리플릿 (통합 개발 환경)", extract: "리플릿(Replit)은 사용자들이 브라우저를 사용하여 코드를 작성하고 앱과 웹사이트를 만들 수 있게 한다. 이 플랫폼은 실시간 채팅 피드를 통한 실시간 다중 사용자 편집 기능을 포함하여 다양한 협업 기능도 갖추고 있다. 또한 다음을 포함한 50개 이상의 프로그래밍 및 언어를 지원한다. 자바, 파이썬, 그리고 HTML, 또한 사용자가 앱 및 웹 사이트를 개발 할 수 있다 이 사이트는 코드 호스팅 플랫폼인 깃허브와 통합되어 있어 깃허브에서 프로젝트를 가져오고 실행할 수 있는 방법을 제공한다. 사용자는 또한 글리치 에서 프로젝트를 가져올 수 있다 이 서비스는 Replit과 유사한 서비스를 제공한다", url: "https://ko.wikipedia.org/wiki/%EB%A6%AC%ED%94%8C%EB%A6%BF_(%ED%86%B5%ED%95%A9_%EA%B0%9C%EB%B0%9C_%ED%99%98%EA%B2%BD)" },
  "robinhood": { lang: "ko", title: "로빈후드 (기업)", extract: "로빈후드(Robinhood)는 미국 캘리포니아주 멘로 파크에 본사를 가진 온라인으로 핸드폰을 통해 주식을 거래하는 플랫폼을 제공하는 기업이다. 2013년 4월 18일에 블라디미르 테네프와 바이주 바트에 의해 설립되었으며 세계적으로 2020년 당시 천 삼백만의 사용자를 보유하고 있다.", url: "https://ko.wikipedia.org/wiki/%EB%A1%9C%EB%B9%88%ED%9B%84%EB%93%9C_(%EA%B8%B0%EC%97%85)" },
  "rubrik": { lang: "en", title: "Rubrik", extract: "Rubrik, Inc. is an American cloud data management and data security company based in Palo Alto, California, founded in January 2014. The company is listed on the New York Stock Exchange after going public in April 2024.", url: "https://en.wikipedia.org/wiki/Rubrik" },
  "salesloft": { lang: "en", title: "Salesloft", extract: "Salesloft is a sales engagement platform. The company was founded in September 2011. Though its original product offering focused on sales development, the company has since expanded its platform to offer functionality for the entire sales organization.", url: "https://en.wikipedia.org/wiki/Salesloft" },
  "servicenow": { lang: "ko", title: "서비스나우", extract: "서비스나우(ServiceNow, Inc.)는 샌타클래라에 본사를 둔 미국의 소프트웨어 회사로, 자동화된 비즈니스 워크플로를 생성하고 관리하기 위한 클라우드 컴퓨팅 플랫폼을 제공한다. 이 회사는 프레드 루디가 2003년에 설립했으며, 뉴욕 증권거래소(티커 심볼: NOW)에 상장되어 있으며 S&P 100 및 S&P 500 지수의 구성 요소이다. 2018년 포브스 잡지는 이 회사를 세계에서 가장 혁신적인 기업 목록에서 1위로 선정했다.", url: "https://ko.wikipedia.org/wiki/%EC%84%9C%EB%B9%84%EC%8A%A4%EB%82%98%EC%9A%B0" },
  "singlestore": { lang: "en", title: "SingleStore", extract: "SingleStore is a distributed, relational, SQL database management system (RDBMS) that features ANSI SQL support, designed to handle data ingest, transaction processing, and query processing.", url: "https://en.wikipedia.org/wiki/SingleStore" },
  "spotify": { lang: "ko", title: "스포티파이", extract: "스포티파이(Spotify)는 2006년에 설립된 스웨덴의 음악 스트리밍 및 미디어 서비스 제공 업체이다. 이 회사는 2018년부터 룩셈부르크에 있고 러셀 1000 지수를 구성하는 지주회사, Spotify Technology S.A.를 통해 뉴욕 증권 거래소에서 공개적으로 거래된 Spotify AB에 의해 운영된다. 스포티파이의 본부는 스웨덴 스톡홀름에 있고 본사는 미국 뉴욕에 있다.", url: "https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%8F%AC%ED%8B%B0%ED%8C%8C%EC%9D%B4" },
  "squarespace": { lang: "ko", title: "스퀘어스페이스", extract: "스퀘어스페이스(Squarespace, Inc.)는 뉴욕시에 본사를 둔 미국의 웹사이트 구축 및 호스팅 회사이다. 웹사이트 구축 및 호스팅을 위한 서비스형 소프트웨어를 제공하며 사용자가 미리 구축된 웹 사이트 템플릿과 끌어서 놓기 요소를 사용하여 웹 페이지를 만들고 수정할 수 있도록 한다.", url: "https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%80%98%EC%96%B4%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4" },
  "stripe": { lang: "ko", title: "스트라이프 (기업)", extract: "스트라이프(Stripe, Inc.)는 미국 캘리포니아주 사우스 샌프란시스코와 아일랜드 더블린에 본사를 두고 있는 아일랜드계 미국인 다국적 금융 서비스 및 SaaS(서비스형 소프트웨어) 회사이다. 이 회사는 주로 전자 상거래 웹사이트와 모바일 애플리케이션을 위한 결제 처리 소프트웨어와 애플리케이션 프로그래밍 인터페이스를 제공한다.", url: "https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%8A%B8%EB%9D%BC%EC%9D%B4%ED%94%84_(%EA%B8%B0%EC%97%85)" },
  "sumup": { lang: "en", title: "SumUp", extract: "SumUp is a British financial technology company headquartered in London. SumUp’s primary product is an EMV card reader and a number of online payment and bank account system for merchants and businesses.", url: "https://en.wikipedia.org/wiki/SumUp" },
  "synthesia": { lang: "en", title: "Synthesia (company)", extract: "Synthesia Limited is a British multinational artificial intelligence company based in London, United Kingdom. It is a synthetic media-generation software developer and creator of AI-generated video content, including audio-visual agents and cloned avatars. Britain's largest generative-AI firm, it is used by 70% of FTSE 100 and over 90% of Fortune 100 companies.", url: "https://en.wikipedia.org/wiki/Synthesia_(company)" },
  "thought-machine": { lang: "en", title: "Thought Machine", extract: "Thought Machine is a London-based cloud banking technology company that was founded in 2014 by Paul Taylor. It operates in the United Kingdom, Singapore, the United States, and Australia.", url: "https://en.wikipedia.org/wiki/Thought_Machine" },
  "thumbtack": { lang: "en", title: "Thumbtack (company)", extract: "Thumbtack is an American online home services marketplace that allows users to locate and hire professionals for home improvement projects.", url: "https://en.wikipedia.org/wiki/Thumbtack_(company)" },
  "trustpilot": { lang: "en", title: "Trustpilot", extract: "Trustpilot Group plc, founded in 2007, is a Danish consumer business that operates a review website hosting reviews of businesses worldwide. As of June 2025, Trustpilot hosts 330 million reviews and has 60 million monthly active users. The site offers freemium services to businesses. It has been criticised for its hosting of fake reviews, and for allowing companies to remove negative reviews.", url: "https://en.wikipedia.org/wiki/Trustpilot" },
  "twilio": { lang: "en", title: "Twilio", extract: "Twilio Inc. is an American cloud communications company based in San Francisco, California, which provides programmable communication tools for making and receiving phone calls, sending and receiving text messages, and performing other communication functions using its web service APIs.", url: "https://en.wikipedia.org/wiki/Twilio" },
  "twitch": { lang: "ko", title: "트위치", extract: "트위치(영어: Twitch)는 비디오 게임 라이브 스트리밍 전용 인터넷 개인 방송 서비스이다. 미국 샌프란시스코를 본사로 두고 있으며 2011년 6월 6일부터 시작되었다. 2014년 7월 25일에는 구글이 약 10억 달러(한화 1조 200억원)에 인수를 검토 중이라고 보도되었으나 8월 25일 아마존닷컴이 9억 7,000만 달러를 모두 현금으로 지불하여 인수했다.", url: "https://ko.wikipedia.org/wiki/%ED%8A%B8%EC%9C%84%EC%B9%98" },
  "verkada": { lang: "ko", title: "버카다", extract: "버카다(영어: Verkada Inc.)는 샌머테이오에 본사를 둔 미국의 보안 기술 기업이다. 이 회사는 비디오 카메라, 접근 제어 시스템, 환경 센서와 같은 보안 장비를 클라우드 기반 머신 비전 및 인공지능과 결합한다.", url: "https://ko.wikipedia.org/wiki/%EB%B2%84%EC%B9%B4%EB%8B%A4" },
  "visa": { lang: "ko", title: "비자 (기업)", extract: "비자(VISA Inc., VISA)는 21,000여개의 금융기관들이 합작하여 만든 글로벌 벤처기업으로, 마스터카드보다 앞서 창업되었다. VISA는 재귀 약자로 Visa International Service Association을 뜻한다. 본사는 미국 캘리포니아주 샌프란시스코에 있다. BIN은 4로 시작한다.", url: "https://ko.wikipedia.org/wiki/%EB%B9%84%EC%9E%90_(%EA%B8%B0%EC%97%85)" },
  "wayflyer": { lang: "en", title: "Wayflyer", extract: "Wayflyer is an Irish non-bank lender and inventory finance company which was founded in 2019 in Dublin, Ireland with a focus on consumer brands. It provides finance through invoice discounting and factoring with a focus on revenue-based financing. The company lends mainly to e-commerce and technology based companies which generate income from advertising and non-recurring revenue streams.", url: "https://en.wikipedia.org/wiki/Wayflyer" },
  "woven-by-toyota": { lang: "en", title: "Woven by Toyota, Inc.", extract: "Woven by Toyota, Inc. is the mobility technology subsidiary of Toyota Motor Corporation, creating and managing the software for Toyota's vehicle operating system, automated driving, and safety. It has founded and managed an investment fund, Woven Capital.", url: "https://en.wikipedia.org/wiki/Woven_by_Toyota%2C_Inc." },
};
